#!/bin/sh

cd /var/www/planet.emacsen.org/

if [ "x$1" = "xloud" ]; then
    /usr/local/bin/python2 venus/planet.py en.ini
    /usr/local/bin/python2 venus/planet.py ru.ini
    /usr/local/bin/python2 venus/planet.py zh.ini
else
    /usr/local/bin/python2 venus/planet.py en.ini > /dev/null 2>&1
    /usr/local/bin/python2 venus/planet.py ru.ini > /dev/null 2>&1
    /usr/local/bin/python2 venus/planet.py zh.ini > /dev/null 2>&1
fi
